# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Access Key Updated 05/02/2022

name: '0.6$(rev:.r)'

trigger:
- master

pr:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Build'
  displayName: 'Build'
  jobs:
  - job:
    displayName: 'Build on Ubuntu'
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '10.x'
        checkLatest: true

    - task: TfxInstaller@3
      displayName: 'Use Node CLI for Azure DevOps'
      inputs:
        version: 'v0.9.x'
        checkLatest: true

    - task: Npm@1
      displayName: 'Install NPM Packages'
      inputs:
        command: 'install'
        workingDir: './sysdig-scan-task/'
        verbose: false

    - task: Bash@3
      displayName: 'Compile Javascript'
      inputs:
        targetType: 'inline'
        script: 'tsc'
        workingDirectory: './sysdig-scan-task/'

    - task: PackageAzureDevOpsExtension@3
      displayName: 'Package Extension: $(Build.SourcesDirectory)'
      name: 'packageStep'
      inputs:
        rootFolder: '$(Build.SourcesDirectory)'
        outputPath: '$(Build.ArtifactStagingDirectory)/sysdig-secure-inline-scanning-task.vsix'
        publisherId: 'IgorEulalio'
        extensionId: 'sysdig-scan-task'
        extensionTag: '-build'
        extensionVersion: '$(Build.BuildNumber)'
        updateTasksVersion: true
        updateTasksVersionType: 'patch'
        extensionVisibility: 'private'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish vsix'
      inputs:
        targetPath: '$(packageStep.Extension.OutputPath)'
        publishLocation: 'pipeline'
        artifact: 'vsix'
      condition: succeededOrFailed()

- stage: "PublishDev"
  displayName: 'Publish Private (Dev)'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  dependsOn: 'Build'
  jobs:
    - deployment:
      environment: Publisher IgorEulalio (Dev)
      strategy:
        runOnce:
         deploy:
          steps:

          - task: TfxInstaller@3
            displayName: 'Use Node CLI for Azure DevOps'
            inputs:
              version: '0.9.x'
              checkLatest: true

          - task: PublishAzureDevOpsExtension@3
            name: 'publishDev'
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'Marketplace Publishing'
              fileType: 'vsix'
              vsixFile: '$(Pipeline.Workspace)/vsix/sysdig-secure-inline-scanning-task.vsix'
              publisherId: 'IgorEulalio'
              extensionId: 'sysdig-scan-task'
              extensionTag: '-dev'
              updateTasksVersion: false
              extensionVisibility: 'privatepreview'
              noWaitValidation: true

          - task: IsAzureDevOpsExtensionValid@3
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'Marketplace Publishing'
              method: 'vsix'
              vsixFile: '$(publishDev.Extension.OutputPath)'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish vsix'
            inputs:
              publishLocation: pipeline
              targetPath: '$(publishDev.Extension.OutputPath)'
              artifact: 'dev'
            condition: succeededOrFailed()

- stage: 'PublishPreview'
  displayName: 'Publish Preview'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn: 'PublishDev'
  jobs:
    - deployment:
      environment: Publisher Igor Eulalio (Preview)
      strategy:
        runOnce:
         deploy:
          steps:

          - task: TfxInstaller@3
            displayName: 'Use Node CLI for Azure DevOps'
            inputs:
              version: '0.9.x'
              checkLatest: true

          - task: PublishAzureDevOpsExtension@3
            name: 'publishPreview'
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'Marketplace Publishing'
              fileType: 'vsix'
              vsixFile: '$(Pipeline.Workspace)/vsix/sysdig-secure-inline-scanning-task.vsix'
              publisherId: 'IgorEulalio'
              extensionId: 'sysdig-scan-task'
              updateTasksVersion: false
              extensionVisibility: 'publicpreview'
              extensionPricing: 'free'
              noWaitValidation: true

          - task: IsAzureDevOpsExtensionValid@3
            inputs:
              connectTo: 'VsTeam'
              connectedServiceName: 'Marketplace Publishing'
              method: 'vsix'
              vsixFile: '$(publishPreview.Extension.OutputPath)'

          - task: PublishPipelineArtifact@1
            displayName: 'Publish vsix'
            inputs:
              publishLocation: pipeline
              targetPath: '$(publishPreview.Extension.OutputPath)'
              artifact: 'prod'
            condition: succeededOrFailed()

          - task: GitHubRelease@1
            inputs:
              gitHubConnection: 'Github'
              repositoryName: '$(Build.Repository.Name)'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'userSpecifiedTag'
              tag: 'v$(Build.BuildNumber)'
              title: 'v$(Build.BuildNumber)'
              releaseNotesSource: 'inline'
              assets: '$(publishProd.Extension.OutputPath)*'
              changeLogCompareToRelease: 'lastFullRelease'
              changeLogType: 'issueBased'
              changeLogLabels: '[{ "state" : "closed" }]'
