name: Build and release extension

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install tfx-cli and typescript
      run: |
        npm install -g tfx-cli
        npm install -g typescript
    
    - name: Build release
      run: |
        make build

        
    - name: Publish release
      env:
        AZURE_DEVOPS_ACCESS_TOKEN: ${{ secrets.AZURE_DEVOPS_ACCESS_TOKEN }}
      run: |
        make publish