name: Sync Versions on PR

on:
  pull_request:
    branches:
      - main

jobs:
  sync-versions:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'skip-version-sync') == false
    defaults:
      run:
        shell: nix develop --command bash {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23

      - name: Enable Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@84c0677f58dcedf3b91f8223ce36a9ea5b3c84b7 # v15
        with:
          use-flakehub: false

      - name: Check for version change
        id: version_changed
        run: |
          git fetch origin main
          if git diff --name-only origin/main...HEAD | grep -q "sysdig-cli-scan-task/package.json"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Run sync script
        if: steps.version_changed.outputs.changed == 'true'
        run: |
          chmod +x ./sync_versions.sh
          ./sync_versions.sh

      - name: Commit and push changes
        if: steps.version_changed.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "ci: synchronize versions"
            git push
          else
            echo "No changes to commit."
          fi
